# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    tunda:
        container_name: tunda
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        expose:
            - 8000
        volumes:
        - .:/usr/src/app
        - ./public:/usr/src/app/public
        depends_on:
            - tunda_db
            - phpmyadmin
        networks:
            - sail
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - 80:80
        depends_on:
            - tunda
        environment:
            NGINX_FPM_HOST: tunda
            NGINX_ROOT: /usr/src/app/public
        networks:
            - sail
    tunda_db:
        container_name: tunda_db
        restart: always
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    phpmyadmin:
        container_name: phpmyadmin
        image: 'phpmyadmin:latest'
        ports:
            - 9080:80
        depends_on:
            - tunda_db
        networks:
            - sail
        environment:
            - PMA_ARBITRARY=1
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local